apiVersion: v1
kind: Secret
metadata:
  name: executor.env
  namespace: staging
type: Opaque
data:
  MNEMONIC: ZXhhbXBsZQ==
  CACHE_TTL: NjA=
  MAX_KEYS: MzA=
  PORT: MzAwMA==
  RPC: aHR0cHM6Ly9ycGMub3JhaS5pbw==
  LCD: aHR0cHM6Ly9sY2Qub3JhaS5pbw==
  CHAIN_ID: T3JhaWNoYWlu
  DENOM: b3JhaQ==
  CONTRACT: b3JhaTEwanN0NWdoMjM5dHZoNTRmZnNmZnVxdXAyaGo2NnE1NHF3M2p1ZzAydnh3cHo3cTBmeWtxY3VjZWtq
  INTERVAL: MTAwMDA=
  GAS_MULTIPLIER: Mi4z
  GAS_PRICE: MC4wMDM=
