---
apiVersion: v1
kind: Service
metadata:
  name: metadata
spec:
  type: NodePort
  selector:
    app: metadata
    tier: backend
  ports:
    - name: "http"
      port: 5051
      targetPort: 5051
      nodePort: 31103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
  labels:
    app: metadata
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
      tier: backend
  template:
    metadata:
      labels:
        app: metadata
        tier: backend
    spec:
      initContainers:
        - name: init-redis
          image: busybox:1.36.1
          command:
            [
              "sh",
              "-c",
              "until nslookup redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis; sleep 2; done",
            ]
        - name: init-mysql
          image: busybox:1.36.1
          command:
            [
              "sh",
              "-c",
              "until nslookup mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done",
            ]
        - name: migrate-database
          image: kawaiiislands/social-login-metadata:1.0.0
          envFrom:
            - secretRef:
                name: mysql-secret
          command: ["sh", "-c", "npm run migrate"]
      containers:
        - name: metadata
          image: kawaiiislands/social-login-metadata:1.0.0
          ports:
            - containerPort: 5051
              name: app-port
          envFrom:
            - secretRef:
                name: mysql-secret
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
