---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: metadata
    tier: mysql
  ports:
    - port: 3306
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metadata-mysql
  labels:
    app: metadata
    tier: mysql
spec:
  selector:
    matchLabels:
      app: metadata
      tier: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: metadata
        tier: mysql
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: mysql
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mysql
          image: mysql:8.0.33
          ports:
            - containerPort: 3306
              name: db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: pvc-metadata
              subPath: mysql
          resources:
            limits:
              cpu: "500m"
              ephemeral-storage: "1Gi"
              memory: "1Gi"
            requests:
              cpu: "500m"
              ephemeral-storage: "1Gi"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: mysql-secret

  volumeClaimTemplates:
    - metadata:
        name: pvc-metadata
        labels:
          app: pvc-metadata
      spec:
        storageClassName: fast-storageclass
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast-storageclass
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-ssd
