---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: metadata
    tier: redis
  ports:
    - port: 6379
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-metadata
  labels:
    app: metadata
    tier: redis
spec:
  selector:
    matchLabels:
      app: metadata
      tier: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: metadata
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine3.18
          ports:
            - containerPort: 6379
          envFrom:
            - secretRef:
                name: mysql-secret
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
