version: "3"

services:
  redis:
    restart: always
    image: redis:alpine3.18
    env_file:
      - ./.env
    ports:
      - "6379:6379"
  mysql:
    restart: always
    image: mysql:5.7
    command: --max_allowed_packet=67108864 # 64 MB
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - metadata-mysql:/var/lib/mysql
  metadata:
    restart: always
    depends_on:
      - mysql
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5051:5051/tcp"
    volumes:
      - .:/app
  volumes:
    - metadata-mysql
