version: "3"

services:
  redis:
    restart: always
    image: redis:alpine3.18
    env_file:
      - ./.env.development
    ports:
      - "6379:6379"
  mysql:
    restart: always
    # platform: linux/x86_64
    image: mysql:8.0.33
    env_file:
      - ./.env.development
    ports:
      - "3306:3306"
  metadata:
    restart: "no"
    depends_on:
      - mysql
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    command: "/app/test/run.sh"
